version: 2.1

jobs:
  build/run:
    docker:
    - image: fedora:latest
    steps:
    - run: 
        command: "sudo dnf update"
        name: update

workflows:
  build:
    jobs:
    - build/run
  version: 2
