version: 2.1

executors:
  ex-fedora-latest:
    docker:
      - image: fedora:latest
  ex-ubuntu-latest:
    docker:
      - image: ubuntu:latest


commands:
  fedora-latest-get-deps:
    description: update & get project dependencies / packages for fedora:latest
    steps:
    - run: 
        command: sudo dnf update -y
        name: update
    - run:
        command: sudo dnf install -y gcc gcc-c++ cmake make botan2-devel
        name: install deps
        
  ubuntu-latest-get-deps:
    description: update & get project dependencies / packagesfor ubuntu:latest (lts)
    steps:
    - run:
        command: apt update
        name: update
    - run:
        command: timedatectl set-timezone Europe/Berlin
        name: prepare apt / set timezone
    - run:
        command: apt install -y build-essential cmake libbotan-2-dev
        name: install deps
        
  cmake-build:
    description: build with cmake
    steps:
    - run:
       command: |
         cmake -S . -B build
         cmake --build build
       name: build
    - persist_to_workspace:
        root: .
        paths: build
        
  test-fastca:
    description: test fastca
    steps:      
    - attach_workspace:
        at: .
    - run:
        command: echo -e "testpw\ntestpw" | build/fastca testhost
       

jobs:
  build-fedora-latest:
    executor: ex-fedora-latest    
    steps:
    - checkout
    - fedora-latest-get-deps
    - cmake-build
        
  test-fedora-latest:
    executor: ex-fedora-latest
    steps:
    - fedora-latest-get-deps
    - test-fastca
    
    
  build-ubuntu-latest:
    executor: ex-ubuntu-latest    
    steps:
    - checkout
    - ubuntu-latest-get-deps
    - cmake-build
        
  test-ubuntu-latest:
    executor: ex-ubuntu-latest
    steps:
    - ubuntu-latest-get-deps
    - test-fastca
    
    
workflows:
  build:
    jobs:
    - build-fedora-latest
    - test-fedora-latest:
        requires:
          - build-fedora-latest
          
    
    - build-ubuntu-latest
    - test-ubuntu-latest:
        requires:
          - build-ubuntu-latest
  
  version: 2
