version: 2.1

executors:
  ex:
    docker:
      - image: fedora:latest

jobs:
  build:
    executor: ex    
    steps:
    - checkout
    - run: 
        command: sudo dnf update -y
        name: update
    - run:
        command: sudo dnf install -y gcc gcc-c++ cmake make botan2-devel
        name: install deps
    - run:
        command: |
          cmake -S . -B build
          cmake --build build
        name: build
        
  test:
    executor: ex
    steps:
    - attach_workspace:
        at: .
    - run:
        command: echo -e "testpw\ntestpw" | build/fastca testhost

workflows:
  build:
    jobs:
    - build
    - test:
        requires:
          - build
  version: 2
