# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
    - image: fedora:latest
    steps:
    - run: 
      command: sudo dnf update
      name: update

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  test-workflow:
    # Run the welcome/run job in its own container
    jobs:
      - build
