version: 2.1

jobs:
  build:
    docker:
    - image: fedora:latest
    steps:
    - run: 
        command: "sudo dnf update -y"
        name: update
    - run:
        command: "sudo dnf install -y gcc gcc-c++ cmake botan2-devel"

workflows:
  build:
    jobs:
    - build
  version: 2
