name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
      - name: apt install
        run: sudo apt install libbotan-2-dev
      - name: make build dir
        run: mkdir build
      - name: cd build dir
        run: cd build
      - name: cmake
        run: cmake ..
      - name: build
        run: make
    
